In [1]:
import re
import moval
import itertools
import pickle
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

## Let's check the model parameters first (pickle)

In [2]:
# pickle_path_org = 'HAM_classification_auc_max_class_probability-conf_ts-model_False.pkl'
# pickle_path_cs = 'HAM_classification_auc_max_class_probability-conf_ts-model_True.pkl'
pickle_path_org = 'Cardiac_segmentation_f1score_max_class_probability-conf_ts-model_False.pkl'
pickle_path_cs = 'Cardiac_segmentation_f1score_max_class_probability-conf_ts-model_True.pkl'

In [3]:
with open(pickle_path_org, 'rb') as file:
    loaded_ckpt = pickle.load(file)
org_param = loaded_ckpt["param"]
print(org_param)

[2.15856791]


In [4]:
loaded_ckpt["fitted_perf"]

[array([0.99646271, 0.98787011, 0.9738901 , 0.98169065]),
 array([0.99678466, 0.99032625, 0.97505624, 0.98380507]),
 array([0.99676482, 0.98717578, 0.96650855, 0.96115645]),
 array([0.99688776, 0.98189425, 0.952292  , 0.95797355]),
 array([0.99670683, 0.97823324, 0.93886129, 0.87453876]),
 array([0.99681181, 0.95219137, 0.88996374, 1.        ]),
 array([0.99678584, 0.90916552, 0.86848216, 1.        ]),
 array([0.9968786 , 0.98045014, 0.95549856, 0.95857876]),
 array([0.99706113, 0.9878092 , 0.96586252, 0.97162753]),
 array([0.9970459 , 0.98632613, 0.96852134, 0.97851277]),
 array([0.99705897, 0.99260908, 0.97472492, 0.98319   ]),
 array([0.99729827, 0.99114026, 0.97387948, 0.97932898]),
 array([0.9971984 , 0.98708847, 0.96131711, 0.97209308]),
 array([0.99709702, 0.98349368, 0.96744622, 0.9717301 ]),
 array([0.997115  , 0.98244183, 0.96835519, 0.97083377]),
 array([0.99629635, 0.97189373, 0.94215582, 0.96127364]),
 array([0.99663547, 0.95731945, 0.92015265, 0.82019221]),
 array([0.9969

In [5]:
len(loaded_ckpt["fitted_perf"])

156

In [6]:
print(np.mean(loaded_ckpt["fitted_perf"]))

0.9688713121637205


In [7]:
with open(pickle_path_cs, 'rb') as file:
    loaded_ckpt = pickle.load(file)
cs_param = loaded_ckpt["param"]
print(cs_param)

[1.         4.59311228 5.41432676 6.112498  ]


In [8]:
loaded_ckpt["fitted_perf"]

[array([0.9997936 , 0.90921061, 0.85949425, 0.85081939]),
 array([0.99983804, 0.91945987, 0.86372489, 0.86736549]),
 array([0.99979262, 0.90819834, 0.82665436, 0.81944925]),
 array([0.99983078, 0.89640487, 0.78969442, 0.80531886]),
 array([0.99979363, 0.89150792, 0.76196788, 0.68613096]),
 array([0.99983904, 0.841678  , 0.69936717, 1.        ]),
 array([0.99982457, 0.75854206, 0.67855958, 1.        ]),
 array([0.99989676, 0.90627285, 0.80945939, 0.79029709]),
 array([0.99985138, 0.92200538, 0.83244782, 0.82204857]),
 array([0.99983685, 0.90313796, 0.84980394, 0.83661274]),
 array([0.99985678, 0.92908326, 0.87684925, 0.84385824]),
 array([0.99982735, 0.91268528, 0.8604991 , 0.81821451]),
 array([0.99977068, 0.89046712, 0.81563986, 0.78373519]),
 array([0.99972826, 0.8792495 , 0.83067513, 0.77812674]),
 array([0.99975138, 0.86992749, 0.83270498, 0.77454906]),
 array([0.99933107, 0.85183216, 0.78491083, 0.75250252]),
 array([0.999894  , 0.84621031, 0.75183686, 0.67002394]),
 array([0.9999

In [9]:
print(np.mean(loaded_ckpt["fitted_perf"]))

0.8759788441935924
